### ISSUE TITLE
Questions on the data

### ISSUE THREAD

**Issue by mwmaclean** [brainhack-school2020/johnaldmcfist-neonatalNiPype#1]
Hello Daniel,

Your project seems really interesting!
I was wondering:
1) Do you have access to control data?
2) What is your current sample size?

Thanks!

**Comment by johnaldmcfist** [comment]
1. I have some control data available but not many because in our current ethical framework it isn't justifiable to scan babies on the second day of life. This data is used depending on the scientific question.
2. My total sample size is around 45 babies born with asphyxia and 4 healthy controls. These babies were scanned at 3 timepoints, day-2, day-10 and day-30 of life.
